Xwayland: Handle minimize request
riverwm/river pull request #501
Opened 2022-01-04 12:52 UTC by novakne

Fix X11 clients getting stuck minimized, and displaying a black screen
after they lose focus.

Fixes #500

2022-01-04 22:27 UTC, ifreund requested changes
Thanks for taking a look at this!

2022-01-04 22:27 UTC, ifreund commented on river/XwaylandView.zig
> +    self.view.applyPending();
This should just call `xwayland_surface.setMinimized()` directly. This is an implementation detail of xwayland and should not leak out in to the rest of the code.

This also needs a comment explaining why we need to do this.

2022-01-05 06:37 UTC, novakne commented on river/XwaylandView.zig
> +}
Whoops my bad I deleted the function that called this since it was useless and forgot to delete it

2022-01-05 17:25 UTC, ifreund commented on river/XwaylandView.zig
> +fn handleRequestMinimize(
This comment and the code below do not match the findings and fix in the linked sway issue/PR...

2022-01-18 15:13 UTC, ifreund approved these changes
Thanks for the fix! I've just improved the comments slightly before pushing this to master.

2022-01-18 15:15 UTC, closed without merging

2022-01-18 15:16 UTC, ifreund commented
It seems github doesn't like what I did so this doesn't like what I did so this doesn't say "merged." Fear not though, it was merged.