rivertile: Use saturating addtion
riverwm/river pull request #510
Opened 2022-01-13 12:15 UTC by novakne

As far as I could tell this is the only occurrence where we can replace it. Grepping around, the only other case of `maxInt(T)` are use to set a value. Grepping for `math` also doesn't return any `math.mul/add/...`

2022-01-13 13:06 UTC, ifreund requested changes
Nice, we can make it even better though :)

2022-01-13 13:06 UTC, ifreund commented on rivertile/main.zig
> +                            '+' => output.main_count = output.main_count +| @intCast(u32, arg),
```suggestion
                            '+' => output.main_count +|= @intCast(u32, arg),
```

2022-01-13 13:19 UTC, novakne commented on rivertile/main.zig
> +                            '+' => output.main_count = output.main_count +| @intCast(u32, arg),
Ah yeah, obviously, done!

2022-01-13 13:30 UTC, novakne commented
Fixed a typo in the commit message

2022-01-14 23:44 UTC, ifreund approved these changes
LGTM, thanks!

2022-01-14 23:45 UTC, merged